### ISSUE TITLE
Need documentations

### ISSUE THREAD

**Issue by kevinresol** [fponticelli/thx.culture#8]
I am looking for a culture library when I reached thx.culture, this library looks rich in contents but I am not sure how to get started.

Basically my tasks mainly include formatting dates, numbers and money(currency) into localized form.

Docs / getting started guides are appreciated :)

**Comment by fponticelli** [comment]
What you are looking for is (thx.format)[https://github.com/fponticelli/thx.format]. it uses `thx.culture` for the localization info and adds many ways to localize numbers, dates and such.

**Comment by kevinresol** [comment]
Oh, how can i miss that?! Thanks!

**Comment by fponticelli** [comment]
Not a problem and I should probably mention that in the readme.
